### ISSUE TITLE
Fixed version supported for liltoon regarding lilMaterialBaker function

### ISSUE THREAD

**Issue by Spokeek** [sayunana/lilToon2MToon#2]
Similar to the issue upstreamed at the liltoon project at https://github.com/lilxyzw/lilToon/issues/209

Right now when using the latest version of the liltoon project, the **lilMaterialBaker** function is not available.

Is it because the function is still not available publicly and only in dev, or if it got limited, can we know what commit to use from the liltoon project to be able to use this batch bake project (that is really cool by the way) .

![image](https://github.com/user-attachments/assets/d2ba5044-b1b9-4606-911d-bf6ba80268ba)

**Comment by sayunana** [comment]
そうです。

このツールはliltoonの新しい関数を使用していますが、現在の最新バージョンにはマージされていません。

以下のブランチをUnityのUPMで登録することで使用できますが、日本語のみの対応になっているので不便かもしれません。

https://github.com/lilxyzw/lilToon.git?path=Assets/lilToon#dev


そのうち英語切り替え機能もを作りますね。

-----------------------------------
Google Translate


That's right.


This tool uses new functions from liltoon, but they have not been merged into the latest version.


You can use it by registering the following branch in Unity's UPM, but it only supports Japanese, so it may be inconvenient.


https://github.com/lilxyzw/lilToon.git?path=Assets/lilToon#dev


I'll make an English switching function soon.

**Comment by Spokeek** [comment]
Perfect, i'll keep this opened in the meantime.

**Comment by sayunana** [comment]
こんにちは。
0.3.1以降のバージョンで言語を変更できるように修正しました。
Google翻訳を使用して一括で変更したので、文章に間違いがあったらpull requestを出してもらえると助かります。

---
Google Translate

Hello.
I fixed it so that you can change the language in versions 0.3.1 and later.
I used Google Translate to make the changes all at once, so if you find any mistakes in the text, I would appreciate it if you could submit a pull request.

![image](https://github.com/user-attachments/assets/e0f11fbb-b0c5-477c-a444-483fb6c3a43f)
